import './globals.css';
import './theme-config.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NavBar from './NavBar';
import { Container, Theme } from '@radix-ui/themes';
import AuthProvider from './auth/Provider';
import ReactQueryClientProvider from './QueryClientProvider';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.variable}>
        <ReactQueryClientProvider>
          <AuthProvider>
            <Theme appearance="light" accentColor="purple">
              <NavBar />
              <main className="p-5">
                <Container>{children}</Container>
              </main>
            </Theme>
          </AuthProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
